name: nightly

on:
  push:
    branches:
      - main
  workflow_dispatch: { }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set VERSION and COMMIT
        shell: bash
        run: |
          set -euo pipefail

          # Short SHA (7 chars)
          VERSION=${GITHUB_SHA:0:7}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          # Extract commit message from the event payload safely
          if [ -n "${GITHUB_EVENT_PATH:-}" ] && [ -f "$GITHUB_EVENT_PATH" ]; then
            COMMIT=$(jq -r '.head_commit.message // ""' "$GITHUB_EVENT_PATH" | sed -E 's/(.*) <.*@.*>/\1/g;t')
          else
            COMMIT="${{ github.event.head_commit.message }}"
          fi
          # Trim whitespace
          COMMIT=$(printf "%s" "$COMMIT" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
          echo "COMMIT=$COMMIT" >> $GITHUB_ENV
          echo "Set VERSION=$VERSION and COMMIT=$COMMIT"

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle (produce installable APK)
        shell: bash
        run: |
          set -euo pipefail

          echo "Building assembleNightly and assembleDebug (debug is signed with debug key)"
          ./gradlew assembleNightly assembleDebug

          # Prefer debug APK (installable), then prefer non-unsigned non-split APKs, then fall back to first APK.
          apk_path=$(find app/build/outputs -type f -name "app-debug*.apk" | head -n 1 || true)
          if [ -z "$apk_path" ]; then
            apk_path=$(find app/build/outputs -type f -name "*.apk" ! -name "*-unsigned.apk" ! -name "*split-*.apk" | head -n 1 || true)
          fi
          if [ -z "$apk_path" ]; then
            apk_path=$(find app/build/outputs -type f -name "*.apk" | head -n 1 || true)
          fi

          if [ -z "$apk_path" ]; then
            echo "ERROR: no APK found under app/build/outputs"
            exit 2
          fi

          echo "Found APK to upload: $apk_path"
          mkdir -p app/build
          cp "$apk_path" "app/build/${{ env.VERSION }}.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          path: app/build/${{ env.VERSION }}.apk

      - name: Upload APK to Discord
        shell: bash
        env:
          ROLE: ${{ secrets.DISCORD_PING_ROLE_ID }}
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          message=$(echo "<@&${{ env.ROLE }}> **${{ env.VERSION }}**\n${{ env.COMMIT }}")
          curl -F "payload_json={\"content\":\"${message}\"}" \
          -F "echo_beta=@app/build/${{ env.VERSION }}.apk" \
          ${{ env.WEBHOOK }}

      - name: Upload APK to Telegram
        shell: bash
        env:
          BOT_ID: ${{ secrets.TELEGRAM_BOT_ID }}
          CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          THREAD_ID: ${{ secrets.TELEGRAM_THREAD_ID }}
        run: |
          regex='s/[\_\*\[\]\(\)\~\`\>\#\+\-\=\|\{\}\.\!]/\\&/g'
          message=$(printf "*Nightly Release*\n${{ env.COMMIT }}" | sed -E "$regex")
          curl -F "chat_id=${{ env.CHANNEL_ID }}" \
          -F "message_thread_id=${{ env.THREAD_ID }}" \
          -F "document=@app/build/${{ env.VERSION }}.apk" \
          -F "caption=${message}" \
          -F "parse_mode=MarkdownV2" \
          https://api.telegram.org/bot${{ env.BOT_ID }}/sendDocument
